Repository mju-likelion/hackathon-team3-web, pull requests merged in 2023-08, with the labels that each got.

#17 Feat/#9 education game page
  src/App.js
  src/assets/data/Content_Choice_Dummy.json
  src/assets/data/Content_Fill_Dummy.json
  src/assets/data/Content_Short_Dummy.json
  src/assets/data/SideBar_DummyData.json
  src/assets/data/keeps
  src/assets/images/logout_icon.svg
  src/assets/images/next_icon.svg
  src/assets/images/search_icon.svg
  src/components/CircleButton.js
  src/components/Content.js
  src/components/Header.js
  src/components/ProgressRateBar.js
  src/components/SideBar.js
  src/components/SquareButton.js
  src/components/Type_Choice.js
  src/components/Type_FillBlank.js
  src/components/Type_ShortInput.js
  src/index.js
  src/pages/Education/AdvancedGame.js
  src/pages/Education/BasicGame.js
  src/pages/Education/EducationSelect.js
  src/styles/GlobalStyle.js
  src/styles/Theme.js
Labels: enhancement

#18 Feature/#16 my page
  package.json
  src/App.js
  src/assets/images/LeftArrow.svg
  src/assets/images/RightArrow.svg
  src/components/Header.js
  src/pages/Main/Main.js
  src/pages/Main/MainBanner.js
  src/pages/Main/keeps
  src/pages/MyPage/MyPageAccount.js
  src/pages/MyPage/MyPageCategory.js
  src/pages/MyPage/MyPageEducation.js
  src/styles/Theme.js
  yarn.lock
Labels: enhancement

#24 Feature/#22 my page change password
  package.json
  src/pages/MyPage/ChangePassword.js
  src/pages/MyPage/ChangePasswordInput.js
  src/pages/MyPage/MyPageAccount.js
  src/pages/MyPage/Validation.js
  yarn.lock
Labels: enhancement

#21 객관식 보기 선택 상태, 그에 따른 제출 구현 - #19
  src/assets/data/Content_Choice_Dummy.json
  src/assets/data/Content_Fill_Dummy.json
  src/assets/data/Content_Short_Dummy.json
  src/assets/data/Rate_DummyData_Advanced.json
  src/assets/data/Rate_DummyData_Basic.json
  src/assets/data/SideBar_DummyData.json
  src/assets/data/SideBar_DummyData_Advanced.json
  src/assets/data/SideBar_DummyData_Basic.json
  src/components/ButtonLong.js
  src/components/ChoiceCircle.js
  src/components/CircleButton.js
  src/components/Content.js
  src/components/ProgressRateBar.js
  src/components/SideBar.js
  src/components/SquareButton.js
  src/components/Type_Choice.js
  src/components/Type_FillBlank.js
  src/components/Type_ShortInput.js
  src/pages/Education/AdvancedGame.js
  src/pages/Education/BasicGame.js
  src/pages/Education/EducationSelect.js
  src/pages/Game/Type_Choice.js
  src/pages/Game/Type_FillBlank.js
  src/pages/Game/Type_ShortInput.js
  src/pages/Join/Join.js
  src/pages/Login/Login.js
  src/pages/Post/keeps
  src/styles/GlobalStyle.js
  src/styles/Theme.js
Labels: enhancement

#28 SideBar API 연결
  package.json
  src/api/Axios.js
  src/api/GetChapters.js
  src/api/GetRate.js
  src/components/SideBar.js
  src/pages/Education/AdvancedGame.js
  src/pages/Education/BasicGame.js
  yarn.lock
Labels: enhancement

#36 feat: 목차 API, Content 연결
  src/api/GetChapter.js
  src/assets/images/bulb_icon.svg
  src/components/Content.js
  src/components/HelpModal.js
  src/components/SideBar.js
  src/pages/Education/BasicGame.js
  yarn.lock
Labels: enhancement

#37 Feature/#26 my page change password api
  .gitignore
  .idea/.gitignore
  .idea/hackathon-team3-web.iml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  src/api/PatchPassword.js
  src/pages/MyPage/ChangePassword.js
  src/pages/MyPage/ChangePasswordInput.js
  src/pages/MyPage/Validation.js
Labels: enhancement

#42 feat: login api 연결
  src/App.js
  src/api/LoginApi.js
  src/pages/Login/Login.js
Labels: enhancement

#40 Feature/#33 join api
  src/api/JoinApi.js
  src/components/Input.js
  src/pages/Join/Join.js
  src/pages/Login/Login.js
Labels: enhancement

#44 feat: 회원 탈퇴 api 연결
  src/api/DeleteUser.js
  src/pages/MyPage/MyPageAccount.js
Labels: enhancement

#47 feat: 챕터 완료 상태에 따른 목차 접근 구현
  package.json
  src/api/GetChapter.js
  src/api/GetChapters.js
  src/api/GetRate.js
  src/api/PostScoring.js
  src/components/ChoiceCircle.js
  src/components/Content.js
  src/components/SideBar.js
  src/pages/Education/BasicGame.js
  yarn.lock
Labels: enhancement

#49 버튼 활성화
  src/components/Content.js
  src/components/SideBar.js
  src/pages/Education/BasicGame.js
  src/pages/Game/Type_Choice.js
  src/pages/Game/Type_FillBlank.js
  src/pages/Game/Type_ShortInput.js
Labels: enhancement

#51 Feature/#1 main page
  .idea/inspectionProfiles/Project_Default.xml
  src/pages/Education/AdvancedGame.js
  src/pages/Main/Main.js
  src/pages/MyPage/MyPageAccount.js
  src/pages/MyPage/MyPageCategory.js
Labels: enhancement

#53 Feature/#52 modify main mypage
  src/api/PatchPassword.js
  src/components/ProgressRateBar.js
  src/pages/Main/Main.js
  src/pages/Main/MainBanner.js
  src/pages/MyPage/ChangePassword.js
  src/pages/MyPage/ChangePasswordInput.js
  src/pages/MyPage/MyPageAccount.js
  src/pages/MyPage/MyPageCategory.js
  src/pages/MyPage/MyPageEducation.js
Labels: enhancement

#57 feat: 헤더 로고추가
  src/assets/images/surfing-logo.png
  src/components/Header.js
Labels: enhancement

#55 feat: 문제 이동시 input value 초기화 및 UI 수정
  src/api/GetChapter.js
  src/api/GetChapters.js
  src/api/PostScoring.js
  src/components/ChoiceCircle.js
  src/components/Content.js
  src/components/HelpModal.js
  src/components/SideBar.js
  src/pages/Education/BasicGame.js
  src/pages/Game/Type_FillBlank.js
  src/pages/Game/Type_ShortInput.js
Labels: enhancement

#67 Feature/#52 modify main mypage
  src/pages/Main/Main.js
  src/pages/Main/MainBanner.js
Labels: enhancement

#66 Education page 컴포넌트 병합
  src/App.js
  src/components/Content.js
  src/pages/Education/AdvancedGame.js
  src/pages/Education/EducationSelect.js
  src/pages/Education/Game.js
Labels: enhancement

#70 feat: 기초 학습 완료 후 심화 학습 페이지로 리다이렉션
  src/pages/Education/Game.js
Labels: enhancement

#63 fix: login 상태 수정, 학습하기 로그인상태 연결
  src/Hooks/ValidationYup.js
  src/api/GetUserInfo.js
  src/components/Header.js
  src/pages/Education/EducationSelect.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/MyPage/MyPageAccount.js
Labels: enhancement

#71 Fix: SideBar 즉시 렌더링 되지 않는 문제 해결
  src/components/SideBar.js
  src/pages/Education/Game.js
Labels: enhancement

#73 feat: 빈칸 width 수정
  src/components/Header.js
  src/pages/Game/Type_FillBlank.js
Labels: enhancement

#74 Feature 완료 페이지 구현
  src/App.js
  src/components/WaveSVG.js
  src/pages/Education/Complete.js
  src/pages/Education/Game.js
  src/styles/GlobalStyle.js
Labels: enhancement

#76 비밀번호 에러코드 로직 수정
  src/api/PatchPassword.js
  src/pages/MyPage/ChangePassword.js
  src/pages/MyPage/ChangePasswordInput.js
  src/pages/MyPage/Validation.js
Labels: enhancement

#78 Add false animation
  src/components/Content.js
Labels: enhancement

#79 UI 사이즈 수정 및 폴더 구조 수정
  src/App.js
  src/Hooks/Validation.js
  src/api/Auth/DeleteUser.js
  src/api/Auth/GetUserInfo.js
  src/api/Auth/JoinApi.js
  src/api/Auth/LoginApi.js
  src/api/Auth/LogoutApi.js
  src/api/Auth/PatchPassword.js
  src/api/Game/GetChapter.js
  src/api/Game/GetChapters.js
  src/api/Game/GetRate.js
  src/api/Game/PostScoring.js
  src/assets/data/Content_Choice_Dummy.json
  src/assets/data/Content_Fill_Dummy.json
  src/assets/data/Content_Short_Dummy.json
  src/assets/data/Rate_DummyData_Advanced.json
  src/assets/data/Rate_DummyData_Basic.json
  src/assets/data/SideBar_DummyData_Advanced.json
  src/assets/data/SideBar_DummyData_Basic.json
  src/components/Button/ButtonLong.js
  src/components/Button/ChoiceCircle.js
  src/components/Button/CircleButton.js
  src/components/Game/Content.js
  src/components/Game/HelpModal.js
  src/components/Game/SideBar.js
  src/components/Game/SquareButton.js
  src/components/Game/Type_Choice.js
  src/components/Game/Type_FillBlank.js
  src/components/Game/Type_ShortInput.js
  src/components/Header.js
  src/components/Input.js
  src/components/Main/MainBanner.js
  src/components/Main/WaveSVG.js
  src/components/MyPage/ChangePasswordInput.js
  src/components/MyPage/MyPageCategory.js
  src/pages/Education/Complete.js
  src/pages/Education/EducationSelect.js
  src/pages/Education/Game.js
  src/pages/Error/NotFound.js
  src/pages/Join/Join.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/MyPage/ChangePassword.js
  src/pages/MyPage/MyPageAccount.js
  src/pages/MyPage/MyPageEducation.js
Labels: documentation, enhancement

#81 Chore/#80 edit readme
  README.md
  src/hooks/Validation.js
  src/hooks/ValidationYup.js
  src/pages/Join/Join.js
  src/pages/Login/Login.js
  src/pages/MyPage/ChangePassword.js
Labels: documentation

#85 feat: 반응형 UI
  README.md
  src/components/Button/ChoiceCircle.js
  src/components/Game/Content.js
  src/components/Game/SideBar.js
  src/components/Game/Type_Choice.js
  src/components/Game/Type_FillBlank.js
  src/components/Game/Type_ShortInput.js
  src/components/Header.js
  src/components/MyPage/MyPageCategory.js
  src/pages/Education/EducationSelect.js
  src/pages/Education/Game.js
  src/pages/Main/Main.js
  src/pages/MyPage/MyPageEducation.js
Labels: enhancement
